apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashshop-backend-deployment
  namespace: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smashshop-backend
  template:
    metadata:
      labels:
        app: smashshop-backend
    spec:
      containers:
      - name: smashshop-backend
        image: thanh8804/smash-shop-backend-image:10
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: smashshop-backend-secret