apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashshop-frontend-deployment
  namespace: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smashshop-frontend
  template:
    metadata:
      labels:
        app: smashshop-frontend
    spec:
      containers:
      - name: smashshop-frontend
        image: thanh8804/smash-shop-frontend-image:18
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: smashshop-frontend-secret