apiVersion: v1
kind: Service
metadata:
  name: smashshop-frontend-service
  namespace: application-deployment
spec:
  type: NodePort
  selector:
    app: smashshop-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003
