apiVersion: v1
kind: Service
metadata:
  name: smashshop-backend-service
  namespace: application-deployment
spec:
  type: NodePort
  selector:
    app: smashshop-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30002
